export const REQUEST_ACCESS_CODE = "REQUEST_ACCESS_CODE";
export const VERIFY_ACCESS_CODE = "VERIFY_ACCESS_CODE";
export const SET_AUTH_STATUS = "SET_AUTH_STATUS";
export const RESET_AUTH_MESSAGE = "RESET_AUTH_MESSAGE";

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";

export const LOGOUT = "LOGOUT";

//SERVICE
export const REQUEST_POST_CAPTION = "REQUEST_POST_CAPTION";
export const REQUEST_POST_CAPTION_SUCCESS = "REQUEST_POST_CAPTION_SUCCESS";
export const REQUEST_POST_CAPTION_FAILURE = "REQUEST_POST_CAPTION_FAILURE";

export const REQUEST_SAVE_CAPTION = "REQUEST_SAVE_CAPTION";
export const SAVE_CAPTION_SUCCESS = "SAVE_CAPTION_SUCCESS";
export const SAVE_CAPTION_FAILURE = "SAVE_CAPTION_FAILURE";

export const GENERATE_POST_IDEAS_REQUEST = "GENERATE_POST_IDEAS_REQUEST";
export const GENERATE_POST_IDEAS_SUCCESS = "GENERATE_POST_IDEAS_SUCCESS";
export const GENERATE_POST_IDEAS_FAILURE = "GENERATE_POST_IDEAS_FAILURE";

export const GENERATE_CAPTIONS_FROM_IDEA_REQUEST =
  "GENERATE_CAPTIONS_FROM_IDEA_REQUEST";
export const GENERATE_CAPTIONS_FROM_IDEA_SUCCESS =
  "GENERATE_CAPTIONS_FROM_IDEA_SUCCESS";
export const GENERATE_CAPTIONS_FROM_IDEA_FAILURE =
  "GENERATE_CAPTIONS_FROM_IDEA_FAILURE";

export const RESET_POST_CAPTION_AND_IDEA = "RESET_POST_CAPTION_AND_IDEA";

//PROFILE
export const REQUEST_USER_CONTENTS = "REQUEST_USER_CONTENTS";
export const RECEIVE_USER_CONTENTS = "RECEIVE_USER_CONTENTS";

export const UNSAVE_CONTENT = "UNSAVE_CONTENT";
export const UNSAVE_CONTENT_SUCCESS = "UNSAVE_CONTENT_SUCCESS";
export const UNSAVE_CONTENT_FAILURE = "UNSAVE_CONTENT_FAILURE";

//THEME
export const TOGGLE_THEME = "TOGGLE_THEME";

// DATA
export const SOCIAL_NETWORK_PROVIDER = ["Facebook", "Instagram", "Twitter"];
export const TONES = [
  "Funny",
  "Serious",
  "Professional",
  "Friendly",
  "Casual",
  "Inspirational",
];
